### ISSUE TITLE
Segreti svelati

### ISSUE THREAD

**Issue by ftrole** [SWException/users#4]
EPIC SECURITY PATCH NEEDED: issue segreta e vaga, non si può dire altro in questa sede, per localizzare la vulnerabilità riferirsi alla mail

**Comment by ivanfurlan** [comment]
Messo come variabile d'ambiente, ma il commit resta. Poco male, le credenziali hanno solo permessi di lettura e l'unico in scrittura è per aggiungere un account ad un gruppo. 
Possibili conseguenze:
- Privacy degli utenti
- Un cliente può mettersi i permessi per diventare venditore

Direi che per il nostro progetto sono di poco conto e sorvolerei

**Comment by ftrole** [comment]
Grazie Ivan, direi top
